// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwxmtupzbmodlvcjlpch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3eG10dXB6Ym1vZGx2Y2pscGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDY2MTAsImV4cCI6MjA2NTQ4MjYxMH0.PEf8l6eVsxnPvq1PDTmF4arU_SYoONpOAinZ_DZJ7Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);